FROM nginx:latest
WORKDIR /usr/share/nginx/html
COPY /CESIUM/ /usr/share/nginx/html/
# COPY web/catastro/ /usr/share/nginx/html/catastro/
# COPY web/webchat/ /usr/share/nginx/html/webchat/

# COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]